# "Include 'server.port' property with value 8081 and try launching the application"
# (the doc's whole point here: account and loan can't both default to 8080)
spring.application.name=loan-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.com.cognizant.loan=debug
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n
