# "Include 'server.port' property with value 8081 and try launching the application"
# (Account uses the default 8080; only Loan needs an explicit override to avoid the port clash)
spring.application.name=account-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.com.cognizant.account=debug
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n
